### ISSUE TITLE
Do GCM3 GDP and population outputs

### ISSUE THREAD

**Issue by bpbond** [JGCRI/gcamdata#636]
This is not ideal, but after discussion with @pralitp and @d3y419 it seems better to implement GCAM3 outputs for now. (See #337 .) The problem is that it's not a simple removal of unneeded outputs; rather doing so changes a number of downstream outputs, and so removing all the GCAM3 stuff complicates our V1 comparison. @russellhz estimates we're talking 4-8 hours of work to put them in for

* L102.GDP.R
* L201.Pop_GDP_scenarios.R
* L242.Bld_Inc_Elas_scenarios.R
* L252.Trn_Inc_Elas_scenarios.R

Yes, this work will probably be ripped back out in the 6-12 month timeframe, but it's a small investment and allows a cleaner, simpler trip to V1.

Russell, you good with this? At your convenience.

**Comment by russellhz** [comment]
Sounds good!

**Comment by rplzzz** [comment]
Just a thought, would it be easier to cut these outputs out of the comparison output, instead of adding them to the new output?

**Comment by bpbond** [comment]
Thanks, Robert. Yes, we can easily exclude things, but that's not the problem. Rather, it's that the GCAM3 outputs flow into other downstream data products that we _do_ want to verify for version 1.

**Comment by rplzzz** [comment]
_Do_ we want to verify them?  If they used GCAM3 data to calculate, then they are junk.  we could just remove all of the downstream GCAM3 products.  Or are you saying that GCAM3 values are being used to calculate values that are ostensibly GCAM4 data?  If that's what's happening, then the old data system is simply _wrong_ and should be fixed.  (This, btw, is one of the best arguments against keeping obsolete data around "just in case".)

**Comment by bpbond** [comment]
My understanding is that GCAM3 data flow into ostensibly non-GCAM3 outputs, but roping in @pralitp and @d3y419 for a more precise answer.

**Comment by pralitp** [comment]
@pkyle was the one who initially looked into where it was being used so he can better comment on that but in the meantime you can check the comments in #337. 

In any case it isn't clear why the downstream products should be _wrong_.  Obviously most of the data products in the system were created long before the SSPs were finalized (and they are still not in the Core version of the model).  Which socioeconomics should they have used?

**Comment by rplzzz** [comment]
If half the model is using GCAM4 socioeconomics, and the other half is using GCAM3 socioeconomics, then the socioeconomics aren't consistent across the model, which is wrong in my book.

**Comment by pkyle** [comment]
From my memory the issue is that when we switched from "gcam3" pop and gdp to "gssp2" pop and gdp, all of the main, important files got switched over. However some minor ones got omitted that are used for (e.g., and I can't look this up right now) population weighting of degree days in multi country regions, or estimating characteristics of transportation technologies in future years, or perhaps building technology efficiencies. Like, the Europe nonEU region has incorrect weighting between the assumed future efficiencies of our old Western Europe and Eastern Europe, because the country weighting (between turkey (WEUR) and Yugoslavia (EEUR)) used gcam3 population and not gssp2. Fixing this should not be hard, though it would require a dedicated task. But the flip side is that not fixing it won't sink the battleship.

**Comment by pralitp** [comment]
I wonder if we are just talking past each other.  To be clear I'm not apposed to removing the GCAM3 socioeconomics but I think there is enough complication and would change result that I would rather have that as it's own proposal and not mid stream of the DSR.

> If half the model is using GCAM4 socioeconomics, and the other half is using GCAM3 socioeconomics, then the socioeconomics aren't consistent across the model, which is wrong in my book.

Again maybe we are really on the same page.  I don't think there is anything wrong in using the socioeconomics to further derive assumptions in other chunks.  But this opens us to to generating inconsistent inputs files, especially given that we don't have a GCAM4 socioeconomics but instead several SSPs (and the so called gSSPs).  Dropping the use of the GCAM3 assumptions won't be sufficient in resolving consistency issues.  Instead we would have to generate several versions of each input file that uses the socioeconomics (I'm not really a fan of this) or come up with some broader strategy for generating alternative scenarios in `gcamdata`.  However we kicked the can down the road for the broader scenario strategy.

**Comment by rplzzz** [comment]
@pralitp My intention was that we would do a quick core model proposal to patch the old data system, then regenerate the comparison data.  However, if the consensus is that it really would be easier to continue generating the GCAM3 data, then I won't object further.  I'm just trying to save us the effort of updating a bunch of code that is basically obsolete.
